#pragma config(Motor,  port2,           rightMotor1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftMotor1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftMotor2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           shooterArm,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           shooter,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           intakeArm,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          release,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                           - Dual Joystick Control with Arm - 1 Remote -                            *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*  The Group 6 buttons on the top-right of the VEXnet Joystick are used to raise and lower an arm.   *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
|*    Motor - Port 6          armMotor             VEX Motor           Arm motor                      *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

task main()
{
  while(1 == 1)
  {
    //Driving Motor Control
    motor[leftMotor1] = vexRT[Ch3] / 2;
    motor[leftMotor2] = vexRT[Ch3] / 2;
    motor[rightMotor1] = vexRT[Ch2] / 2;
    motor[rightMotor2] = vexRT[Ch2] / 2;

    //intakeArm Control
    if(vexRT[Btn5U] == 1)
    {
      motor[intakeArm] = 40;
    }
    else if(vexRT[Btn5D] == 1)
    {
      motor[intakeArm] = -40;
    }
    else
    {
      motor[intakeArm] = 0;
    }
     //intake Control
    if(vexRT[Btn8U] == 1)
    {
      motor[intake] = 50;
    }
    else if(vexRT[Btn8D] == 1)
    {
      motor[intake] = -50;
    }
    else
    {
      motor[intake] = 0;
    }
     //release Control
    if(vexRT[Btn8L] == 1)
    {
      motor[release] = 160;
    }
    else if(vexRT[Btn8R] == 1)
    {
      motor[release] = -160;
    }
    else
    {
      motor[release] = 0;
    }
     //shooterArm Control
    if(vexRT[Btn6U] == 1)
    {
      motor[shooterArm] = 40;
    }
    else if(vexRT[Btn6D] == 1)
    {
      motor[shooterArm] = -40;
    }
    else
    {
      motor[shooterArm] = 0;
    }
       //shooter Control
    if(vexRT[Btn7U] == 1)
    {
      motor[shooter] = 200;
    }
    else if(vexRT[Btn7D] == 1)
    {
      motor[shooter] = -100;
    }
    else
    {
      motor[shooter] = 0;
    }
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
